name = "zeno-backend"
main = "src/index.js"
compatibility_date = "2024-08-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# environment variables will go here later

[observability.logs]
enabled = false
